services:
  microcart.order.api:
    image: ${DOCKER_REGISTRY-}microcartorderapi
    build:
      context: .
      dockerfile: src/Services/microcart.order.api/Dockerfile
    ports:
      - 5100:8080
      - 5101:8081

  microcart.database:
    image: postgres:latest
    container_name: microcart-postgres
    environment:
      - POSTGRES_DB=microcart
      - POSTGRES_USER=microcart
      - POSTGRES_PASSWORD=microcart
    volumes:
      - ./.containers/microcart-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=eduarroyo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    ports:
      - 5000:80